screenshot command

diff --git a/X/xinitrc b/X/xinitrc
--- a/X/xinitrc
+++ b/X/xinitrc
@@ -1,27 +1,38 @@
-#
-# location: ~/.xinitrc
-#
+systemctl --user import-environment DISPLAY # dunst fails to start otherwise
 
+#xautolock -time 10 -locker "i3lock -c 000000 -e -f" &
 dwmstatus 2>&1 >/dev/null &
 
+# man xkeyboard-config
+# localectl --no-convert set-x11-keymap us,dvorak pc105 dvp, caps:escape,compose:ralt,grp:win_space_toggle
 #setxkbmap -layout us,dvorak -variant dvp, -option grp:ctrls_toggle 
 setxkbmap us dvp
 setxkbmap -option caps:escape # Srly f*ck caps
 setxkbmap -option 'compose:rctrl'
-#setxkbmap -option 'grp:ctrls_toggle' # why doesn't this work?
+#setxkbmap -option 'grp:shifts_toggle' # Why doesn't this work
+setxkbmap -option 'grp:ctrls_toggle' # Why doesn't this work
 
 nitrogen --restore
 xbindkeys
 
 # Japanese input
-#export GTK_IM_MODULE=fcitx
-#export QT_IM_MODULE=fcitx
-#export SDL_IM_MODULE=fcitx
-#export XMODIFIERS=@im=fcitx
-#fcitx -d # start fcitx as a daemon
+export GTK_IM_MODULE=fcitx
+export QT_IM_MODULE=fcitx
+export SDL_IM_MODULE=fcitx
+export XMODIFIERS=@im=fcitx
 
 # Start picom as daemon
 picom -b
 
+# Start fcitx as a daemon
+fcitx -d
+
 # Do not put anything else below this line!
-while type dwm >/dev/null ; do dwm && continue || break ; done
+case $WM in
+dwm) while type dwm >/dev/null ; do dwm && continue || break ; done ;;
+hypr) exec Hypr ;;
+openbox) exec openbox ;;
+xfce) startxfce4 ;;
+*) while type dwm >/dev/null ; do dwm && continue || break ; done ;;
+esac
+#while type dwm >/dev/null ; do dwm && continue || break ; done
